import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const baseDir = path.resolve(__dirname, '..');

const config = JSON.parse(await fs.readFile(path.join(baseDir, 'openapi/services.json'), 'utf8'));

const combined = {
  openapi: '3.0.3',
  info: {
    title: 'University Management System - Unified API',
    version: '1.0.0',
    description: 'Merged OpenAPI document generated by API Gateway.'
  },
  servers: [{ url: '/api' }],
  paths: {},
  components: {},
  tags: []
};

for (const service of config.services) {
  let spec = null;

  if (service.url) {
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 3000);
      const response = await fetch(service.url, { signal: controller.signal });
      clearTimeout(timeout);
      if (response.ok) {
        spec = await response.json();
      }
    } catch {}
  }

  if (!spec && service.fallbackFile) {
    spec = JSON.parse(await fs.readFile(path.join(baseDir, service.fallbackFile), 'utf8'));
  }

  if (!spec) {
    throw new Error(`No OpenAPI source found for ${service.name}`);
  }

  for (const [p, pathObj] of Object.entries(spec.paths ?? {})) {
    if (!combined.paths[p]) {
      combined.paths[p] = pathObj;
    } else {
      combined.paths[`/services/${service.name}${p}`] = pathObj;
    }
  }

  for (const [componentType, componentValues] of Object.entries(spec.components ?? {})) {
    combined.components[componentType] ??= {};
    for (const [key, value] of Object.entries(componentValues)) {
      const normalizedKey = combined.components[componentType][key] ? `${service.name}_${key}` : key;
      combined.components[componentType][normalizedKey] = value;
    }
  }

  combined.tags.push({ name: service.name, description: `${service.name} (${service.version})` });
}

const outputDir = path.join(baseDir, 'openapi');
await fs.mkdir(outputDir, { recursive: true });
const outputPath = path.join(outputDir, 'combined.openapi.json');
await fs.writeFile(outputPath, JSON.stringify(combined, null, 2), 'utf8');

console.log(`Merged OpenAPI spec written to ${outputPath}`);
