server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location /api/ { proxy_pass http://traefik/; proxy_set_header Authorization $http_authorization; proxy_set_header X-Tenant-ID $http_x_tenant_id; proxy_set_header Host $host; }
  location / { try_files $uri $uri/ /index.html; }
}
