import { promises as fs } from 'fs';
import path from 'path';

export interface ServiceSpecConfig {
  name: string;
  version: string;
  url?: string;
  fallbackFile?: string;
}

interface ServicesConfig {
  services: ServiceSpecConfig[];
}

type OpenApiDocument = Record<string, any>;

async function readOpenApiFile(filePath: string): Promise<OpenApiDocument> {
  const raw = await fs.readFile(filePath, 'utf8');
  return JSON.parse(raw) as OpenApiDocument;
}

export async function loadServicesConfig(baseDir: string): Promise<ServiceSpecConfig[]> {
  const configPath = path.join(baseDir, 'openapi', 'services.json');
  const raw = await fs.readFile(configPath, 'utf8');
  const parsed = JSON.parse(raw) as ServicesConfig;
  return parsed.services;
}

async function fetchServiceSpec(
  service: ServiceSpecConfig,
  baseDir: string,
): Promise<OpenApiDocument> {
  if (service.url) {
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 3000);
      const response = await fetch(service.url, { signal: controller.signal });
      clearTimeout(timeout);
      if (!response.ok) {
        throw new Error(`Unable to load ${service.url}`);
      }
      return (await response.json()) as OpenApiDocument;
    } catch {
      // Fallback to local file below.
    }
  }

  if (!service.fallbackFile) {
    throw new Error(`No OpenAPI source available for ${service.name}`);
  }

  const fallbackPath = path.join(baseDir, service.fallbackFile);
  return readOpenApiFile(fallbackPath);
}

function mergeObjects(target: Record<string, any>, source: Record<string, any>, prefix: string) {
  for (const [key, value] of Object.entries(source ?? {})) {
    const normalizedKey = target[key] ? `${prefix}_${key}` : key;
    target[normalizedKey] = value;
  }
}

export async function buildCombinedSpec(baseDir: string): Promise<OpenApiDocument> {
  const services = await loadServicesConfig(baseDir);

  const combined: OpenApiDocument = {
    openapi: '3.0.3',
    info: {
      title: 'University Management System - Unified API',
      version: '1.0.0',
      description: 'Merged OpenAPI document generated by API Gateway.',
    },
    servers: [{ url: '/' }],
    paths: {},
    components: {},
    tags: [],
  };

  for (const service of services) {
    const spec = await fetchServiceSpec(service, baseDir);

    for (const [specPath, pathObject] of Object.entries(spec.paths ?? {})) {
      if (!combined.paths[specPath]) {
        combined.paths[specPath] = pathObject;
        continue;
      }

      const namespacedPath = `/services/${service.name}${specPath}`;
      combined.paths[namespacedPath] = pathObject;
    }

    const components = spec.components as Record<string, Record<string, any>>;
    for (const [componentType, componentValues] of Object.entries(components ?? {})) {
      combined.components[componentType] ??= {};
      mergeObjects(combined.components[componentType], componentValues, service.name);
    }

    combined.tags.push({
      name: service.name,
      description: `${service.name} (${service.version})`,
    });
  }

  return combined;
}

export async function writeCombinedSpec(baseDir: string): Promise<string> {
  const combined = await buildCombinedSpec(baseDir);
  const outputDir = path.join(baseDir, 'openapi', 'generated');
  await fs.mkdir(outputDir, { recursive: true });

  const outputPath = path.join(outputDir, 'combined.openapi.json');
  await fs.writeFile(outputPath, JSON.stringify(combined, null, 2), 'utf8');

  return outputPath;
}
